### ISSUE TITLE
Amend Readme template to include point-person

### ISSUE THREAD

**Issue by ashfurrow** [RxSwiftCommunity/contributors#27]
We have so many repos that it can be hard to know who to ask for help. Usually the original creator of the repo is the best choice, but finding out who that is could be easier. 

I suggest including instructions to add point-people to readme across our repos. Not a critical change, so we can do this gradually, but I think it's a step in the right direction.

Thoughts @RxSwiftCommunity/contributors ?

**Comment by freak4pc** [comment]
👍 good idea

**Comment by groue** [comment]
Nothing against. But aren't issues the preferred Github way to contact a repo's maintainers? Maybe you're thinking about cross-repos questions.

**Comment by ashfurrow** [comment]
Yeah, what I mean is if a conversation in a GitHub issue needs guidance from someone really familiar with that project, it would help (me, mostly 😛 ) to know who to turn to. Am I making sense?

**Comment by bobgodwinx** [comment]
I would just suggest `maintainers` and add people who are qualified to maintain the repo as maintainers to it. But I bet this is a difficult task. :)

**Comment by fpillet** [comment]
I'd side with @groue. Issues are expected to be the primary way of getting support. Internally, pinging someone directly is obviously a good thing but I fear that people use it too liberally just to get faster support / answers, uselessly increasing the pressure on maintainers.

**Comment by rynecheow** [comment]
I'm not against it.

**Comment by icanzilb** [comment]
I’m also not super excited about being directly responsible for the repos i contributed, i’m afraid many people do not understand what maintainer exactly entails

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by DivineDominion** [comment]
Issues sound good to me; What about adding a line to `CONTRIBUTING.md` about the originator which GitHub will link to when you open an issue?

**Comment by devxoul** [comment]
Agree to @DivineDominion's idea. GitHub has a guide page about [CONTRIBUTING file](https://opensource.guide/starting-a-project/#writing-your-contributing-guidelines) and there is a similar content about maintainers:

> a CONTRIBUTING file is an opportunity to communicate your expectations for contributions, such as:
> * ...
> * How contributors should (or should not) get in touch with you

I think we could add a maintainer section to the CONTRIBUTING file for example:

```
## Maintainers

* Suyeol Jeon (@devxoul)
```

Alternatively we could consider an issue template or a pull request template to let users know who actively maintains the repo.

**Comment by fpillet** [comment]
Going for a CONTRIBUTING file sounds good. This way other community maintainers know where to look at when they need to contact someone, and we make it no-so-obvious for everyone else to reach directly to the maintainer. I've seen (on GitHub or on Slack) some newcomers being particularly pushy for no good reason, trying to avoid this case.

**Comment by ashfurrow** [comment]
Yeah, I think a CONTRIBUTING file strikes a good balance between making it possible to find out who to contact when needed, without making it too easy for people to spam maintainers. If that's the case, I'll open a PR this weekend. More feedback is always welcome.

**Comment by kzaher** [comment]
My 2 cents.

I'm afraid that if we add particular people they will be quoted inside issues and people will assume that will help to resolve their issues more quickly.

I think it could actually create an opposite effect.

It will reduce the chance of somebody else helping them out because they will think it's not their business because they are not quoted, and thus not being asked.

The maintainers of the repo will probably already watch the repo and respond when they have time. I don't see quoting someone will help anyone.

**Comment by bobgodwinx** [comment]
@kzaher You just read my mind with that comment. `It will reduce the chance of somebody else helping them out because they will think it's not their business`  I would suggest that each repo should have more maintainers for a start and that one point person should just stand as a top reference but other maintainers should be able to help when there is an issue. 
[He is a really good link on how opensource contribution should work and I think we should go through this doc.](https://opensource.guide/how-to-contribute/#finding-a-project-to-contribute-to)

**Comment by fpillet** [comment]
@bobgodwinx Again and as suggested before, that's the primary reason why we have Github issues. Some repos are more active than others, and some people (like yourself) helping on multiple repos is great and I don't think we need to change this process -- anyone interested can chime in and respond to issues. Only make sure you get notified if you want to participate.

**Comment by ashfurrow** [comment]
I think some of my intent was miscommunicated – please understand that I'm not interested in increasing the volume of anyone's inbox or making anyone feel like they have to contribute. Our contributor guidelines lay this out specifically:

> Don't ever feel bad for not contributing to open source.
>
> We want contributors to both provide ideas, keep the ship shipping and to take some of the load from others. It is non-obligatory; we're here to have fun.

The problem I opened this issue to solve is this: when help is asked for on a PR or input is requested in a discussion, I'd like some way to alert _only_ the people who are in a position to help. Right now, the only way to ask for help on a given repo is to mention @RxSwiftCommunity/contributors and _everybody_ gets an email. That's a lot of noise that we're all getting right now. I want a solution to be able to know who specifically to turn to when I need help.

I hope that clarifies the motivation behind this issue – sorry for the miscommunication. I borrowed the term "point-person" from Artsy but failed to account for differences between business and open source. I'm looking forward to hearing everyone's ideas about how to improve communication in the org.

**Comment by groue** [comment]
@ashfurrow:

> The problem I opened this issue to solve is this: when help is asked for on a PR or input is requested in a discussion, I'd like some way to alert only the people who are in a position to help. Right now, the only way to ask for help on a given repo is to mention @RxSwiftCommunity/contributors and everybody gets an email.

That's much more clear, thank you.

Yes, ringing all contributors sounds like killing a mosquito with a bazooka (yet the mosquito is killed, which is the desired effect). Now Github lets users watch repos if they want, and this covers a great deal of your needs: the point-persons you look after are likely to be already watching the repos they feel like contributing to. They are notified even before you call all contributors in, actually.

Maybe I've described an ideal world, and not the reality. Maybe some point-persons are not yet watching the repos they would be glad helping with (1). Maybe they get notifications, but answer too late (2). Worse (3): they used to be watching, but stopped because of the high notification volume. Whoever has tried to watch the core http://github.com/ReactiveX/RxSwift may feel what I'm talking about. The flux is high, and was definitely too high for me.

1: People not watching, can be addressed when welcoming new contributors, by inviting them to subscribe to repos.

2: Late answers, is difficult to address. OSS is a living community, with lazy people, vacation weeks, and a quaint cemetery of abandoned projects. The relevance of a point-person named in a forgotten and ageing CONTRIBUTING file is questionable. On the living side, the Github contributors pages are telling me that @icanzilb is the point-person for RxRealm, you take care of NSObject-Rx, @esttorhe and @freak4pc are good entry points to RxViewModel, yours truly maintains RxGRDB, etc. Is this the kind of information you look after? Would you replace or add names in my list?

3: Overwhelmed contributors, is actually very concerning. Especially for the most precious members of this community, those who are able to understand a wide class of Rx-related troubles, and can help in various situations. I don't see how point-persons in several CONTRIBUTING files would address this subject better than conversations between the involved people, but I'm no communication expert.

My wild guess is that you try to address the third point. Strolling around RxSwiftCommunity had me learn that you, @freak4pc, @kzaher, and @fpillet, in no particular order, are pretty active (apologies to other main contributors I hadn't the chance to stumble upon yet). I'd consider you all as a reliable and precious source of information and hints that should not be wasted! And you are not that many.

**Comment by ashfurrow** [comment]
I don't think watching a repo is sufficient; I don't watch a lot of repos I'm on, and it's a read-only mechanism (there's no way to @ the watchers when needed). I rely on the ability for people to seek me out and ask for help when they need it. That information is already available (through git commit history, GitHub commit graphs), I just want to make it a little easier to access.

A tangential point: when someone adds a new library to the org, I'd like them to retain a sense of ownership over the project. A simple "this was originally created by ___" in the readme could go a long way in keeping maintainers more active.

This sounds like a pretty contentious topic – why don't we set up a Google Hangout some time to talk about it face-to-face? Give a 👍 if you'd like to be on the call.

**Comment by freak4pc** [comment]
I think I'd like to add some more thoughts due to the discussion here. 

This is, as @ashfurrow said, a very tricky topic. 

From one hand we want people who have actual serious problems to be able to reach out to project owners. 

On the other hand, I totally understand the worries of some people here. Keeping a project active and developers happy is already a non-trivial job :) People are (on a daily basis) private messaging core contributors on trivial questions that aren't related to the project, but more like a personal tutor, and thats not something any contributor should have to accept (unless they want to). We're all volunteers with very very limited time. 

I think it all boils down to this, as @ashfurrow detailed: 
> The problem I opened this issue to solve is this: when help is asked for on a PR or input is requested in a discussion, I'd like some way to alert only the people who are in a position to help.

Why don't we make a decision that we have a `@Repo/core` on every repository containing the "point people" of a repository? - I'm not sure if it's possible having it work project-level this way, but if yes that would be a solid solution for this case. 

I totally understand (and somewhat relate to) @fpillet's point about the fact we want developers to have access to communicate with project owners but we don't want to make it too obvious / easy, so people don't get too trigger happy and abuse this communication pipeline.

I'm happy to hop on a brainstorming hangout if you guys think that would be helpful :)

**Comment by ashfurrow** [comment]
Wow, having a per-repo core team sounds like a really good compromise. That would also allow members to filter out email sent to them because of their membership to that team (if they want to). How do others feel about this idea?

**Comment by kzaher** [comment]
Hi,

First of all, I would like to say that everybody in this thread are my heroes. Without help from volunteers like you, we couldn't run this.

Having said that, I would like to make your lives as easy as possible.
Everybody here is a volunteer, we help out when we can and when it makes sense for us. I'm assuming that the incentive for helping out and investigating issues is that maintainers are maybe using some of these projects themselves so investigating those issues would make their apps potentially more stable ... or sometimes they are just nice people.

It is my understanding there are two main issues (please correct me if I'm wrong):
* quoting @RxSwiftCommunity/contributors vs quoting some more narrow set of people that creates a lot of noise  
* users getting help faster

If `@RxSwiftCommunity/contributors` creates a lot of noise in someones inbox, please create a filter for it to mark it as read and skip inbox **unless it originated from this repo**. That is a simplest way to solve the noise problem IMHO.

I wish we could somehow ban any form of mentions except for people who have write access to repos. 
From game theoretical point of view it is my belief that quoting serves no one.

**If you have some issue and you are quoting somebody explicitly you are decreasing the chance someone unexpected solving your issue. This is extremely important for scaling the project and this has helped me so much I can't stress this enough.**

**If we assume that somebody is a nice person and responds more quickly to somebody quoting him than everybody will start doing that and swamp his inbox.**

If he doesn't respond more quickly in case somebody quotes him, than quoting is of no use.

**So IMHO responding to quoting punishes those that behave most altruistic.**

My suggestion is simple:
* Let's just use github issues like we've used to.
* If somebody is interested in helping out with some repo, they can just add it to their watch list. 
* In this way nobody needs to have some special permission to help out with some repo.

**Comment by bobgodwinx** [comment]
Can we also talk about pod trunk ? https://github.com/RxSwiftCommunity/RxCoreData/issues/25

**Comment by freak4pc** [comment]
@bobgodwinx This is the same thing really. We need a good way to know the owners of a repo

**Comment by bobgodwinx** [comment]
I don't know... maybe we should form a `Core Team` for this kind of petty problems ? like Apple https://swift.org/community/#communication it's just a suggestion... these are things that should handled immediately and would encourage fast pace development... please correct me if I am wrong.

**Comment by icanzilb** [comment]
@bobgodwinx "these are things that should handled immediately" ? Can you give an example?

**Comment by bobgodwinx** [comment]
@icanzilbI I may have mis-spoken `these are things that should handled immediately` please don't be mad at me I didn't mean it bad . All I was try to say is this: For example we had a `Swift 4.0` release and most frameworks rush to updates but some aren't updated, some #PRs are ready and no one to handle it, I repeat my intention is not to get anyone angry or look pushy but it would be nice to have someone to run to in order to release a ready `update`. I really don't know how to communicate this feeling. Sorry.

**Comment by freak4pc** [comment]
@bobgodwinx I understand what you mean, but I don't agree with "immediately" :) 
The Swift core team is very well paid by Apple, we are all OSS contributors working on our own spare time. 

We need to release versions as soon as possible, but we don't need to pressure anyone's time into this community. 

People who are the sole owners of a Cocoapod need to be extra responsible since the development of the product is blocked without their help (Even if its for adding a second person to help) 

PS please don't take example from Swift - PRs take months to be merged and releases take much longer than our tiny community :D

**Comment by groue** [comment]
@bobgodwinx You can use `pod 'RxCoreData', :git => 'https://github.com/RxSwiftCommunity/RxCoreData.git', :tag => '0.4.0'` in your podfile until @scotteg comes back and give you the keys to `pod trunk push`.

**Comment by freak4pc** [comment]
PS, as a sidenote, I believe we (perhaps with @ashfurrow ?) discussed having Cocoapod owners for RxSwiftCommunity repos always add a secondary person as owner, so there's always a fallback for new version releases. Not sure if we're able to do that but it's beneficial since some of this repos have been sort of abandoned by their original owner.

**Comment by icanzilb** [comment]
@bobgodwinx  Don't worry - I understand the sentiment and the situation when a commercial project is depending on os libs that don't get updated in alignment with your own deadlines.

It's a measured risk that project owners should account for - OS libs (if not sponsored) are moving ahead on their own accord. As an example - last year I had a bad medical issue and a death in the family, many people were angry with me because some of the libs I own didn't get updated and even attacked me personally on social media - this is a situation that OS owners do not get to be in and putting their name on a short-list for emergencies I think is a way to getting into exactly this type of situation.

However, I do think we could find an agreeable solution...

**What if we added a rule** for repos contributed to RxSwiftCommunity to have at least 2 or 3 owners on CocoaPods? And ask people to responsibly "step down" if they are impeded from supporting the lib in long-term - this way we will have the opprotunity for the remaining owner to do releases and meanwhile find someone else interested to step in. This way at least we will not get into situation when the library gets locked out of release cycle on CocoaPods.

**Comment by bobgodwinx** [comment]
@freak4pc @icanzilb sorry for using `immediately` I was just flowing with the keyboard. But thanks you awesome guys understand. @groue thanks for the info.

**Comment by freak4pc** [comment]
> What if we added a rule for repos contributed to RxSwiftCommunity to have at least 2 or 3 owners on CocoaPods? And ask people to responsibly "step down" if they are impeded from supporting the lib in long-term - this way we will have the opprotunity for the remaining owner to do releases and meanwhile find someone else interested to step in.

100% with this, exactly what I wrote above your comment @icanzilb :) 

One more owner is fine. I mean, original owner and someone who's a prominent member of the community (you, me, florent, ash, etc). People who can "in emergencies" deal with at least pushing a new release.

**Comment by bobgodwinx** [comment]
Maybe not step down but just add some else to it will do the job `pod trunk add-owner NAME_OF_LIB another.person@rx.community.org`

**Comment by icanzilb** [comment]
yes, indeed "stepping down" would not be required - I just thought it could be reasonable to ask if one loses interest or is otherwise not able to do maintaining to voice this ("the stepping down") instead of just disappearing 😊

**Comment by orta** [comment]
IMO ( as the guy who receives every admin request on trunk ) you should have a shared private repo, (or use a [keybase git repo](https://keybase.io/blog/encrypted-git-for-everyone ) with credentials for an RxSwift community user account `community@rxswift.com` that is added to every lib here, then anyone can ship a version

**Comment by freak4pc** [comment]
Great idea @orta . I was sort of leaning towards that same solution.

Was hoping to just see Organization-level `pod push` credentials, but that's probably not in the scope of this discussion.  

A singular community@rxswift.com is a relatively easy method but I think a bit easy to exploit. 

Not sure on your idea for a Shared Private Repo - how would that solve it here? Just throwing in an email and password in a private repo seems a bit odd. Is there a different authentication method I'm not aware of ? 

P.S This seems like a bit of a divergence in discussion - I think there are two different questions here

1. How do we deal with reaching out to Repo owners 
2. How do we ship new versions without the owners, if those are not available

The 2nd sort of helps with making the 1st less urgent - I believe; if anyone who's a member can push a pod version, that would make it a bit easier. I'm a bit worried about exploiting this mechanism, but would love any thoughts.

**Comment by scotteg** [comment]
I am fine if someone such as @bobgodwinx wants to take over RxCoreData. Just let me know what I need to do. Thanks

**Comment by bobgodwinx** [comment]
@scotteg I am not taking over RxCoreData. But just the ability to publish updates to cocoapods when necessary. For now can you just trunk it and we would find a solution all together that solves issues. Thanks very much for getting back to the Team.

**Comment by kzaher** [comment]
I'm still a bit confused with the list thing. Everybody on this list should have permissions to create new tags in all of the repos.

If the problem we are trying to solve is that we need to add enable all of the RxSwiftCommunity contributors to publish new cocoapods release, then lets just do what @orta suggests.

**Comment by freak4pc** [comment]
@kzaher I'm not entirely sure what orates solution is. I don't know of Cocoapods' abilities for teams. If there's a straightforward solution let's go ahead and do it. It's been very hard to maintain specs otherwise.

**Comment by esttorhe** [comment]
I think this issue has been greatly beneficial to what Ash originally addressed and also to make us notice some more issues we need to improve.

That being said I think we are discussing now 3 different things in 1 single place which makes it harder to follow and causes a lot of confusion.

I suggest:

1. Closing this issue and opening a new one with the new information; better worded and some of the suggestions addressing the possible solution for a list of people who someone can turn to address certain things
1. Open a new one to discuss how we can properly and easily share release credentials/capabilities
1. Open an issue in `RxCoreData` to see if there's a need for someone to take over the project and see who would want to and could actually take care of the task.

This in order to make discussion cleaner and easier to follow

**Comment by freak4pc** [comment]
I agree :+1: @esttorhe

**Comment by ashfurrow** [comment]
Agreed. https://github.com/RxSwiftCommunity/contributors/issues/29 is already opened, I'll collect info from this thread and open two issues tomorrow. Thanks for the discussion so far everyone – your feedback keeps this community healthy :heart:

**Comment by ashfurrow** [comment]
I've opened the following issues to follow up on this conversation. I'm really time-constrained right now so I might not be able to address them all quickly, but they're there.

- https://github.com/RxSwiftCommunity/contributors/issues/30
- https://github.com/RxSwiftCommunity/contributors/issues/31
- https://github.com/RxSwiftCommunity/RxCoreData/issues/28

**Comment by esttorhe** [comment]
Thanks Ash! 🙏

Don't worry about the time to address them.
I think most of them (maybe sans 31) the community can tackle them by themselves freeing some of your time as well.

–
Esteban Torres
iOS Developer

Phone: (+49)0162-4190-543
Skype: esteban.a.torres.hernandez
Twitter: @esttorhe
