### ISSUE TITLE
Define a solution for organization members to push new version(s) of projects

### ISSUE THREAD

**Issue by bobgodwinx** [RxSwiftCommunity/contributors#29]
### Currently 
As per indication at the moment all the `RxSwiftCommunity` repositories  doesn't have a shared access where contributors could easy make updates and deploy the approved updates when ready. 
### Required 
Discuss and find a solution to this problem where contributors could update and deploy on all fronts without contacting the original creator of the repository.

**Comment by freak4pc** [comment]
Continued discussion from #27 .

This issue is to make a decision on how we can resolve the issue where repo (our Cocoapods, specifically) owners become inactive and are:

* no longer involved with the project; or
* have less time at that specific period of their life

Since we are all working on our spare time, the latter is a very very common scenario. 

Right now the only solution we have is to ask to be added as owners so we can push a new Pod libraries here.

@orta Has suggested a solution of using a Private Shared Repository and/or some common community@rxswift.org email to provide unified authentication/ownership to all RxSwiftCommunity projects. If you could elaborate a bit more on how the `pod` cli tool works here that would be great. 

Would the plan be to just have a single email with a simple password? I think security-wise this is dangerous, so if there's an authentication strategy you thought of that I don't know I'd really love to know about that :)

**Comment by ashfurrow** [comment]
Yeah yeah, I like this discussion! I'm pretty busy this week but will try to chime in when I can. If there're specifics I can answer, please @ me.

**Comment by bobgodwinx** [comment]
I will be handling ` RxCoreData`until we find a solution in here. for the whole community.

**Comment by freak4pc** [comment]
I came up with a great solution for the deployment issue we've been battling. Closing this issue in favor of a new one where I'll describe the solution and gather some feedback before starting with a pilot (on RxAlamofire, probably)
